### ISSUE TITLE
Genesis parameters

### ISSUE THREAD

**Issue by liorzilp** [dymensionxyz/infrastructure#24] opened 2023-01-24 12:50 UTC
## Overview
Currently, the genesis parameters are set in the 'hub-entrypoint.sh' as a fixed list.
For many tests we would need to set different parameters which introduce manual script changes and would be hard to maintain.

## Suggestion
Enable to load a configuration file set as an input parameter. That way we could maintain many setups as configuration files.
The configuration file should allow specifying genesis parameters as well as other configuration such as suggested in https://github.com/dymensionxyz/infrastructure/issues/23

**Comment by omritoptix** [comment] 2023-01-24 12:56
duplicate of #13

**Comment by shaolin-flow** [comment] 2023-01-24 23:52
@liorzilp can we close this issue as duplicate?

**Closed** 2023-09-12 14:08 UTC
Labels: enhancement
